require('plugins')
require('zeroknots.core.options')
require('zeroknots.core.keymaps')
require('zeroknots.core.colorscheme')
require('zeroknots.plugins.comments')
require('zeroknots.plugins.nvim-tree')
require('zeroknots.plugins.lualine')
require('zeroknots.plugins.telescope')
require('zeroknots.plugins.treesitter')
require('zeroknots.plugins.nvim-cmp')
require('zeroknots.plugins.mason')
require('zeroknots.plugins.lspsaga')
require('zeroknots.plugins.lspconfig')
require('zeroknots.plugins.null-ls')
require('zeroknots.plugins.terminal')
require('zeroknots.plugins.hop')
require('zeroknots.plugins.whichkey')
require('zeroknots.plugins.neogit')
require('zeroknots.plugins.indent-blankline')
require('zeroknots.plugins.git-worktree')
require('zeroknots.plugins.bufferline')


